title:    Cristian Burich # your name (or website title) here
logo: "/images/2 croppedb.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
  Hi!
  <br><br>
  This Website is a Work in Progress 
  <br><br>
  <a href="https://www.linkedin.com/in/cristian-burich/">View My LinkedIn Profile</a> 
  <br><br>
  <pdf src="pdf/CV Burich Cristian.pdf?raw=true"/>View my Resume</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
